import xml.etree.ElementTree as et
import xml.dom.minidom as dom

class readFromXML:
    def __init__(self):
        self.xmlTree = et.parse("dirList.xml")
        self.root = self.xmlTree.getroot()
    def updateXML(self):
        self.xmlTree = et.parse("dirList.xml")
        self.root = self.xmlTree.getroot()
    def numberOfDirsInXML(self):
        self.updateXML()
        a = self.root.find("./directories")
        x = a.attrib["numberOfDirs"]
        return int(x) 
    def readDirectory(self, dirN):
        dirToRead = self.root.find("./directories/dir"+str(dirN))
        return dirToRead.text
    def readDriveID(self, dirN):
        dirToRead = self.root.find("./directories/dir"+str(dirN))
        return dirToRead.attrib["driveID"]

class writeToXML:
    def __init__(self):
        self.xmlTree = et.parse("dirList.xml")
        self.root = self.xmlTree.getroot() 
    def writeDirectory(self, absDir, x):
        x = x+1
        directories = self.root.find("./directories")
        directories.attrib["numberOfDirs"] = str(x)
        newDir = et.SubElement(self.root[0], "dir"+str(x))
        newDir.text = absDir
        self.xmlTree.write("dirList.xml")
        self.makePretty()
    def writeDriveID(self, dirN, driveID):
        dirToEdit = self.root.find("./directories/dir"+str(dirN))
        dirToEdit.attrib["driveID"] = driveID
        self.xmlTree.write("dirList.xml")
    def fileToString(self):
        x = et.tostring(self.root)
        return x
    def makePretty(self):
        self.__init__()
        xmlstring = self.fileToString()
        xml = dom.parseString(xmlstring)
        prettyXML = xml.toprettyxml()
        # This line removes excess new lines generated by toprettyxml() function.
        prettyXML = '\n'.join([s for s in prettyXML.splitlines() if s.strip()])
        with open("dirList.xml", 'w+') as f:
            f.write(prettyXML)


if __name__ == '__main__':
    r = readFromXML()
    w = writeToXML()
    #t = xmlTests()
#
#    w.writeDirectory("absDir", r.numberOfDirsInXML())
#    x = r.numberOfDirsInXML()
#    for i in range(1,x+1):
#        print(str(i)+"  "+r.readDirectory(i))
